### Obtener a todos los usuarios
GET https://autenticacion-global-dreamlab.azurewebsites.net/api/user

### Login
POST https://autenticacion-global-dreamlab.azurewebsites.net/api/user/login
Content-Type: application/json

{
   "Id_Credencial": "matriculaNueva",
   "Password": "12345"
}